/**
 * Catálogo central de eventos de auditoria.
 * Garante consistência tipada e previne erros de digitação nos logs.
 */
export const AuditEvent = {
  // --- AUTENTICAÇÃO E SESSÃO ---
  AUTH_LOGIN: "AUTH_LOGIN",
  AUTH_LOGIN_FAILED: "AUTH_LOGIN_FAILED",
  AUTH_LOGOUT: "AUTH_LOGOUT",
  AUTH_REFRESH: "AUTH_REFRESH",
  AUTH_RESET_PASSWORD: "AUTH_RESET_PASSWORD",
  AUTH_VERIFY_EMAIL: "AUTH_VERIFY_EMAIL",
  SESSION_INVALIDATE_ALL: "SESSION_INVALIDATE_ALL",

  // --- USUÁRIOS E PAPÉIS ---
  ROLE_ASSIGN: "ROLE_ASSIGN",
  USER_DEACTIVATE: "USER_DEACTIVATE",
  USER_REACTIVATE: "USER_REACTIVATE",
  USER_PROFILE_UPDATE: "USER_PROFILE_UPDATE",

  // --- LIGA E ESTRUTURA ---
  SEASON_CREATE: "SEASON_CREATE",
  SEASON_ACTIVATE: "SEASON_ACTIVATE",
  SPLIT_CREATE: "SPLIT_CREATE",
  SPLIT_ACTIVATE: "SPLIT_ACTIVATE",
  PHASE_CREATE: "PHASE_CREATE",
  GROUP_CREATE: "GROUP_CREATE",
  PLAYOFF_SERIES_CREATE: "PLAYOFF_SERIES_CREATE",

  // --- TIMES E JOGADORES ---
  TEAM_CREATE: "TEAM_CREATE",
  TEAM_DEACTIVATE: "TEAM_DEACTIVATE",
  PLAYER_CREATE: "PLAYER_CREATE",
  PLAYER_TRANSFER: "PLAYER_TRANSFER",
  PLAYER_STATUS_CHANGE: "PLAYER_STATUS_CHANGE",
  CONTRACT_CLOSE: "CONTRACT_CLOSE",
  CONTRACT_CREATE: "CONTRACT_CREATE",

  // --- DRAFT ---
  DRAFT_CREATE: "DRAFT_CREATE",
  DRAFT_STATUS_CHANGE: "DRAFT_STATUS_CHANGE",
  DRAFT_PICK: "DRAFT_PICK",

  // --- PARTIDAS E MVP ---
  MATCH_CREATE: "MATCH_CREATE",
  MATCH_OFFICIAL_ASSIGN: "MATCH_OFFICIAL_ASSIGN",
  MATCH_START: "MATCH_START",
  MATCH_EVENT_VOID: "MATCH_EVENT_VOID",
  MATCH_FINISH: "MATCH_FINISH",
  MATCH_CANCEL: "MATCH_CANCEL",
  MATCH_POSTPONE: "MATCH_POSTPONE",
  MATCH_STATUS_REVERT: "MATCH_STATUS_REVERT",
  MVP_STATS_COMPUTED: "MVP_STATS_COMPUTED",
  MVP_INSTAGRAM_IMPORT: "MVP_INSTAGRAM_IMPORT",
  MVP_ADMIN_OVERRIDE: "MVP_ADMIN_OVERRIDE",

  // --- INSCRIÇÕES ---
  REGISTRATION_CREATE: "REGISTRATION_CREATE",
  REGISTRATION_STATUS_CHANGE: "REGISTRATION_STATUS_CHANGE",

  // --- AÇÃO SOCIAL E DOAÇÕES ---
  CAMPAIGN_CREATE: "CAMPAIGN_CREATE",
  CAMPAIGN_UPDATE_PUBLISH: "CAMPAIGN_UPDATE_PUBLISH",
  DONATION_RECEIVED: "DONATION_RECEIVED",
  DONATION_CONFIRM: "DONATION_CONFIRM",
  CAMPAIGN_GOAL_REACHED: "CAMPAIGN_GOAL_REACHED",

  // --- E-COMMERCE E INGRESSOS ---
  ORDER_CREATE: "ORDER_CREATE",
  ORDER_STATUS_CHANGE: "ORDER_STATUS_CHANGE",
  ORDER_REFUND: "ORDER_REFUND",
  COUPON_CREATE: "COUPON_CREATE",
  COUPON_APPLIED: "COUPON_APPLIED",
  TICKET_GENERATE: "TICKET_GENERATE",
  TICKET_VALIDATE: "TICKET_VALIDATE",
  TICKET_REVERT: "TICKET_REVERT",

  // --- CONTEÚDO E PATROCINADORES ---
  ARTICLE_PUBLISH: "ARTICLE_PUBLISH",
  ARTICLE_UNPUBLISH: "ARTICLE_UNPUBLISH",
  COMMENT_DELETE: "COMMENT_DELETE",
  MEDIA_UPLOAD: "MEDIA_UPLOAD",
  MEDIA_DELETE: "MEDIA_DELETE",
  SPONSOR_CREATE: "SPONSOR_CREATE",
  SPONSOR_LINK_TEAM: "SPONSOR_LINK_TEAM",
  SPONSOR_LINK_LEAGUE: "SPONSOR_LINK_LEAGUE",

  // --- AUDITORIA / SISTEMA ---
  AUDIT_READ: "AUDIT_READ",
  AUDIT_EXPORT: "AUDIT_EXPORT",
  STATS_RECALCULATE: "STATS_RECALCULATE",
} as const;

export type AuditEventType = keyof typeof AuditEvent;