/**
 * Catálogo central de eventos de auditoria.
 * Garante consistência tipada e previne erros de digitação nos logs.
 */
export const AuditEvent = {
  // --- AUTENTICAÇÃO E SESSÃO ---
  AUTH_LOGIN: "AUTH_LOGIN",
  AUTH_LOGIN_FAILED: "AUTH_LOGIN_FAILED",
  AUTH_LOGOUT: "AUTH_LOGOUT",
  AUTH_REFRESH: "AUTH_REFRESH",
  AUTH_RESET_PASSWORD: "AUTH_RESET_PASSWORD",
  AUTH_VERIFY_EMAIL: "AUTH_VERIFY_EMAIL",
  SESSION_INVALIDATE_ALL: "SESSION_INVALIDATE_ALL",

  // --- USUÁRIOS E PAPÉIS ---
  ROLE_ASSIGN: "ROLE_ASSIGN",
  USER_DEACTIVATE: "USER_DEACTIVATE",
  USER_REACTIVATE: "USER_REACTIVATE",
  USER_PROFILE_UPDATE: "USER_PROFILE_UPDATE",

  // --- LIGA E ESTRUTURA ---
  SEASON_CREATE: "SEASON_CREATE",
  SEASON_ACTIVATE: "SEASON_ACTIVATE",
  SPLIT_CREATE: "SPLIT_CREATE",
  SPLIT_ACTIVATE: "SPLIT_ACTIVATE",
  PHASE_CREATE: "PHASE_CREATE",
  GROUP_CREATE: "GROUP_CREATE",
  PLAYOFF_SERIES_CREATE: "PLAYOFF_SERIES_CREATE",

  // --- TIMES E JOGADORES ---
  TEAM_CREATE: "TEAM_CREATE",
  TEAM_DEACTIVATE: "TEAM_DEACTIVATE",
  PLAYER_CREATE: "PLAYER_CREATE",
  PLAYER_TRANSFER: "PLAYER_TRANSFER",
  PLAYER_STATUS_CHANGE: "PLAYER_STATUS_CHANGE",
  CONTRACT_CLOSE: "CONTRACT_CLOSE",
  CONTRACT_CREATE: "CONTRACT_CREATE",

  // --- DRAFT ---
  DRAFT_CREATE: "DRAFT_CREATE",
  DRAFT_STATUS_CHANGE: "DRAFT_STATUS_CHANGE",
  DRAFT_PICK: "DRAFT_PICK",

  // --- PARTIDAS E MVP ---
  MATCH_CREATE: "MATCH_CREATE",
  MATCH_OFFICIAL_ASSIGN: "MATCH_OFFICIAL_ASSIGN",
  MATCH_START: "MATCH_START",
  MATCH_EVENT_VOID: "MATCH_EVENT_VOID",
  MATCH_FINISH: "MATCH_FINISH",
  MATCH_CANCEL: "MATCH_CANCEL",
  MATCH_POSTPONE: "MATCH_POSTPONE",
  MATCH_STATUS_REVERT: "MATCH_STATUS_REVERT",
  MVP_STATS_COMPUTED: "MVP_STATS_COMPUTED",
  MVP_INSTAGRAM_IMPORT: "MVP_INSTAGRAM_IMPORT",
  MVP_ADMIN_OVERRIDE: "MVP_ADMIN_OVERRIDE",

  // --- INSCRIÇÕES ---
  REGISTRATION_CREATE: "REGISTRATION_CREATE",
  REGISTRATION_STATUS_CHANGE: "REGISTRATION_STATUS_CHANGE",

  // --- AÇÃO SOCIAL E DOAÇÕES ---
  CAMPAIGN_CREATE: "CAMPAIGN_CREATE",
  CAMPAIGN_UPDATE_PUBLISH: "CAMPAIGN_UPDATE_PUBLISH",
  DONATION_RECEIVED: "DONATION_RECEIVED",
  DONATION_CONFIRM: "DONATION_CONFIRM",
  CAMPAIGN_GOAL_REACHED: "CAMPAIGN_GOAL_REACHED",

  // --- E-COMMERCE E INGRESSOS ---
  ORDER_CREATE: "ORDER_CREATE",
  ORDER_STATUS_CHANGE: "ORDER_STATUS_CHANGE",
  ORDER_REFUND: "ORDER_REFUND",
  COUPON_CREATE: "COUPON_CREATE",
  COUPON_APPLIED: "COUPON_APPLIED",
  TICKET_GENERATE: "TICKET_GENERATE",
  TICKET_VALIDATE: "TICKET_VALIDATE",
  TICKET_REVERT: "TICKET_REVERT",

  // --- CONTEÚDO E PATROCINADORES ---
  ARTICLE_PUBLISH: "ARTICLE_PUBLISH",
  ARTICLE_UNPUBLISH: "ARTICLE_UNPUBLISH",
  COMMENT_DELETE: "COMMENT_DELETE",
  MEDIA_UPLOAD: "MEDIA_UPLOAD",
  MEDIA_REJECTED: "MEDIA_REJECTED", // Registra tentativas de upload malicioso
  MEDIA_DELETE: "MEDIA_DELETE",
  SPONSOR_CREATE: "SPONSOR_CREATE",
  SPONSOR_LINK_TEAM: "SPONSOR_LINK_TEAM",
  SPONSOR_LINK_LEAGUE: "SPONSOR_LINK_LEAGUE",

  // --- AUDITORIA / SISTEMA ---
  AUDIT_READ: "AUDIT_READ",
  AUDIT_EXPORT: "AUDIT_EXPORT",
  STATS_RECALCULATE: "STATS_RECALCULATE",

  // --- CRIPTOGRAFIA / SEGURANÇA (Onda 2 - E2.5) ---
  KEY_ROTATION: "KEY_ROTATION",
  ENCRYPTION_FAILURE: "ENCRYPTION_FAILURE",
  TWO_FACTOR_ENCRYPTED: "TWO_FACTOR_ENCRYPTED",

  // --- PRIVACIDADE / LGPD (Onda 2 - E2.6) ---
  CONSENT_GRANT: "CONSENT_GRANT",
  CONSENT_REVOKE: "CONSENT_REVOKE",
  DATA_EXPORT: "DATA_EXPORT",
  USER_DATA_CORRECT: "USER_DATA_CORRECT",
  USER_ANONYMIZE: "USER_ANONYMIZE",
  LGPD_INCIDENT_REGISTER: "LGPD_INCIDENT_REGISTER",
  LGPD_INCIDENT_READ: "LGPD_INCIDENT_READ",
  PARENTAL_CONSENT_VERIFY: "PARENTAL_CONSENT_VERIFY",

  // === E3.1 — Estrutura da Liga ===
  SEASON_UPDATE: "SEASON_UPDATE",
  SEASON_DEACTIVATE: "SEASON_DEACTIVATE",
  SEASON_DELETE: "SEASON_DELETE",
  SPLIT_UPDATE: "SPLIT_UPDATE",
  SPLIT_DEACTIVATE: "SPLIT_DEACTIVATE",
  SPLIT_DELETE: "SPLIT_DELETE",
  PHASE_UPDATE: "PHASE_UPDATE",
  PHASE_REORDER: "PHASE_REORDER",
  PHASE_DELETE: "PHASE_DELETE",
  GROUP_UPDATE: "GROUP_UPDATE",
  GROUP_DELETE: "GROUP_DELETE",
  TEAM_GROUP_ASSIGN: "TEAM_GROUP_ASSIGN",
  TEAM_GROUP_REMOVE: "TEAM_GROUP_REMOVE",

  // === E3.2 — Roster ===
  TEAM_UPDATE: "TEAM_UPDATE",
  TEAM_REACTIVATE: "TEAM_REACTIVATE",
  TEAM_SOCIAL_UPSERT: "TEAM_SOCIAL_UPSERT",
  TEAM_SOCIAL_REMOVE: "TEAM_SOCIAL_REMOVE",
  PLAYER_UPDATE: "PLAYER_UPDATE",
  PLAYER_SOCIAL_UPSERT: "PLAYER_SOCIAL_UPSERT",
  PLAYER_SOCIAL_REMOVE: "PLAYER_SOCIAL_REMOVE",
  PLAYER_DELETE: "PLAYER_DELETE",
  TEAM_DELETE: "TEAM_DELETE",
  CONTRACT_UPDATE: "CONTRACT_UPDATE",
} as const;

// Alias para garantir retrocompatibilidade com o upload.service.ts
export const AUDIT_EVENTS = AuditEvent;

export type AuditEventType = keyof typeof AuditEvent;
